### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by davelassanske** [dancormier/react-native-swipeout#81]
I'm trying to install react-native-swipeout and am getting "npm ERR! cb() never called!"

All other libraries have installed successfully.

OSX 10.11.3
npm 3.8.3

Let me know what info I need to provide to better investigate this issue.

**Comment by davelassanske** [comment]
Following these instructions: https://www.npmjs.com/package/cb-inspector
I have this output:

`cb#21 never called -- errorHandler args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/lib/install.js:214:26
cb#22 never called --  args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function chain at /appname/node_modules/npm/node_modules/slide/lib/chain.js:4:0
cb#49206 never called --  args:2 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/node_modules/slide/lib/bind-actor.js:14:9
cb#49207 never called --  args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/lib/install.js:345:36
cb#49208 never called --  args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function chain at /appname/node_modules/npm/node_modules/slide/lib/chain.js:4:0
cb#49221 never called --  args:2 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/node_modules/slide/lib/bind-actor.js:14:9
cb#49222 never called --  args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/lib/install.js:368:47
cb#49223 never called --  args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function chain at /appname/node_modules/npm/node_modules/slide/lib/chain.js:4:0
cb#49231 never called --  args:2 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/node_modules/slide/lib/bind-actor.js:14:9
cb#49232 never called --  args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/lib/install/and-finish-tracker.js:4:17
cb#49233 never called --  args:0 -- was passed to 1 handler(s) (none called back)
    Passed to function dezalgo at /appname/node_modules/npm/node_modules/dezalgo/dezalgo.js:6:0
cb#49234 never called -- cb args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/lib/install/deps.js:188:17
cb#49235 never called -- cb args:1 -- was passed to 1 handler(s) (none called back)
    Passed to function  at /appname/node_modules/npm/lib/instanpm ERR! cb() never called!`
